# Generated by Django 4.1.5 on 2023-06-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main_skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pluses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('street', models.CharField(max_length=80, null=True)),
                ('postal_code', models.CharField(max_length=5, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=500)),
                ('Dob', models.DateField()),
                ('contanct_number', models.CharField(max_length=100)),
                ('feild', models.CharField(max_length=200, null=True)),
                ('author', models.EmailField(max_length=100)),
                ('slug', models.SlugField(blank=True, default='')),
                ('Main_skills', models.ManyToManyField(to='Employee.main_skill')),
                ('Pluses', models.ManyToManyField(to='Employee.pluses')),
            ],
        ),
    ]
