# Generated by Django 4.1.5 on 2023-05-17 14:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('street', models.CharField(max_length=80, null=True)),
                ('postal_code', models.CharField(max_length=5, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=500)),
                ('Dob', models.DateField()),
                ('contanct_number', models.CharField(max_length=100)),
                ('feild', models.CharField(max_length=200, null=True)),
                ('author', models.EmailField(max_length=100)),
                ('slug', models.SlugField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Main_skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pluses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=500, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(default=datetime.date(2023, 5, 17))),
                ('Employee', models.ForeignKey(default='5', on_delete=django.db.models.deletion.CASCADE, to='Employee.employee')),
                ('company', models.ForeignKey(default='freelance', on_delete=django.db.models.deletion.CASCADE, to='Company.company')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='Main_skills',
            field=models.ManyToManyField(to='Employee.main_skill'),
        ),
        migrations.AddField(
            model_name='employee',
            name='Pluses',
            field=models.ManyToManyField(to='Employee.pluses'),
        ),
    ]
