# Generated by Django 4.1.5 on 2023-05-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_initial'),
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job2',
            field=models.ManyToManyField(related_name='Job_emp', to='Company.job'),
        ),
        migrations.AddField(
            model_name='main_skill',
            name='job1',
            field=models.ManyToManyField(related_name='Job_main', to='Company.job'),
        ),
        migrations.AddField(
            model_name='pluses',
            name='job8',
            field=models.ManyToManyField(related_name='Job_plus', to='Company.job'),
        ),
    ]
