# Generated by Django 4.1.5 on 2023-06-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
