# Generated by Django 4.1.5 on 2023-05-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_initial'),
        ('Employee', '0002_employee_job2_main_skill_job1_pluses_job8'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='job2',
        ),
        migrations.RemoveField(
            model_name='main_skill',
            name='job1',
        ),
        migrations.RemoveField(
            model_name='pluses',
            name='job8',
        ),
        migrations.AddField(
            model_name='employee',
            name='jobs',
            field=models.ManyToManyField(blank=True, related_name='Job_emp', to='Company.job'),
        ),
        migrations.AddField(
            model_name='main_skill',
            name='jobs',
            field=models.ManyToManyField(blank=True, related_name='Job_main', to='Company.job'),
        ),
        migrations.AddField(
            model_name='pluses',
            name='jobs',
            field=models.ManyToManyField(blank=True, related_name='Job_plus', to='Company.job'),
        ),
    ]
