# Generated by Django 4.1.5 on 2023-05-17 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_remove_employee_job2_remove_main_skill_job1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='jobs',
        ),
        migrations.RemoveField(
            model_name='main_skill',
            name='jobs',
        ),
        migrations.RemoveField(
            model_name='pluses',
            name='jobs',
        ),
    ]
