# Generated by Django 4.1.5 on 2023-06-20 00:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_alter_employee_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=500, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(default=datetime.date(2023, 6, 20))),
                ('company', models.CharField(max_length=500)),
                ('Employee', models.ForeignKey(default='5', on_delete=django.db.models.deletion.CASCADE, to='Employee.employee')),
            ],
        ),
    ]
