# Generated by Django 4.1.5 on 2023-06-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='exp',
            name='type',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
