# Generated by Django 4.1.5 on 2023-06-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0008_rename_employee_exp_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exp',
            name='description',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
