# Generated by Django 4.1.5 on 2023-06-21 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0009_alter_exp_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='exp',
            name='Main_skills',
            field=models.ManyToManyField(to='Employee.main_skill'),
        ),
        migrations.AlterField(
            model_name='exp',
            name='end_date',
            field=models.DateField(default=datetime.date(2023, 6, 21)),
        ),
    ]
