# Generated by Django 4.1.5 on 2023-06-23 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0011_remove_job_pluses'),
        ('Employee', '0010_exp_main_skills_alter_exp_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Pluses',
        ),
        migrations.AlterField(
            model_name='exp',
            name='end_date',
            field=models.DateField(default=datetime.date(2023, 6, 23)),
        ),
        migrations.DeleteModel(
            name='Pluses',
        ),
    ]
