# Generated by Django 4.1.5 on 2023-05-17 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('street', models.CharField(max_length=80, null=True)),
                ('postal_code', models.CharField(max_length=5, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=500)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('contanct_number', models.CharField(max_length=100)),
                ('feild', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('author', models.EmailField(max_length=100)),
                ('slug', models.SlugField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=500, null=True)),
                ('salary', models.IntegerField()),
                ('hours', models.IntegerField(null=True)),
                ('slug', models.SlugField(blank=True, default='')),
                ('feild', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
