# Generated by Django 4.1.5 on 2023-05-17 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Employees',
            field=models.ManyToManyField(to='Employee.employee'),
        ),
        migrations.AddField(
            model_name='job',
            name='Main_skill',
            field=models.ManyToManyField(to='Employee.main_skill'),
        ),
        migrations.AddField(
            model_name='job',
            name='Pluses',
            field=models.ManyToManyField(to='Employee.pluses'),
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company'),
        ),
    ]
