# Generated by Django 4.1.5 on 2023-06-18 22:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=500, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(default=datetime.date(2023, 6, 19))),
                ('Employee', models.ForeignKey(default='5', on_delete=django.db.models.deletion.CASCADE, to='Employee.employee')),
                ('company', models.ForeignKey(default='freelance', on_delete=django.db.models.deletion.CASCADE, to='Company.company')),
            ],
        ),
    ]
