# Generated by Django 4.1.5 on 2023-05-17 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='Employees',
        ),
        migrations.RemoveField(
            model_name='job',
            name='Main_skill',
        ),
        migrations.RemoveField(
            model_name='job',
            name='Pluses',
        ),
    ]
