# Generated by Django 4.1.5 on 2023-06-18 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='rating',
        ),
    ]
