# Generated by Django 4.1.5 on 2023-05-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_remove_employee_jobs_remove_main_skill_jobs_and_more'),
        ('Company', '0003_remove_job_employees_remove_job_main_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Employees',
            field=models.ManyToManyField(to='Employee.employee'),
        ),
        migrations.AddField(
            model_name='job',
            name='Main_skill',
            field=models.ManyToManyField(to='Employee.main_skill'),
        ),
        migrations.AddField(
            model_name='job',
            name='Pluses',
            field=models.ManyToManyField(to='Employee.pluses'),
        ),
    ]
