# Generated by Django 4.1.5 on 2023-06-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
        ('Company', '0003_remove_company_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
        migrations.AlterField(
            model_name='job',
            name='Pluses',
            field=models.ManyToManyField(null=True, to='Employee.pluses'),
        ),
    ]
