# Generated by Django 4.1.5 on 2023-06-19 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0005_job_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(default=datetime.date(2023, 6, 20)),
        ),
    ]
