# Generated by Django 4.1.5 on 2023-06-19 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0009_alter_company_description_alter_job_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
